CREATE DATABASE IF NOT EXISTS vk;

SHOW DATABASES;
USE vk;

CREATE TABLE IF NOT EXISTS users (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	firstname VARCHAR(100) NOT NULL,
	lastname VARCHAR(100) NOT NULL,
	email VARCHAR(120) NOT NULL UNIQUE,
	phone VARCHAR(120) NOT NULL UNIQUE,
	created_at DATETIME DEFAULT NOW(),
	updated_at DATETIME DEFAULT NOW() ON UPDATE NOW()
);

DESCRIBE users;

CREATE TABLE profiles (
	user_id INT UNSIGNED NOT NULL PRIMARY KEY,
	sex CHAR(1) NOT NULL,
	birthday DATE,
	hometown VARCHAR(100),
	photo_id INT UNSIGNED NOT NULL
);

DESCRIBE profiles;


CREATE TABLE messages (
	Id INT UNSIGNED NOT NULL PRIMARY KEY,
	from_user_id INT UNSIGNED NOT NULL,
	to_user_id INT UNSIGNED NOT NULL,
	body TEXT NOT NULL,
	important BOOLEAN,
	delivered BOOLEAN,
	created_at DATETIME DEFAULT NOW()
);

DESCRIBE messages;

CREATE TABLE friendship (
	user_id INT UNSIGNED NOT NULL,
	friend_id INT UNSIGNED NOT NULL,
	status VARCHAR(20) NOT NULL,
	requested_at DATETIME DEFAULT NOW(),
	confirmed_at DATETIME,
	PRIMARY KEY (user_id, friend_id)
);

DESCRIBE friendship;

CREATE TABLE communities (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(150) NOT NULL UNIQUE
);

DESCRIBE communities;

CREATE TABLE communities_users (
	community_id INT UNSIGNED NOT NULL,
	user_id INT UNSIGNED NOT NULL,
	PRIMARY KEY (community_id, user_id)
);

DESCRIBE communities_users;

CREATE TABLE media (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	media_type_id INT UNSIGNED NOT NULL,
	user_id INT UNSIGNED NOT NULL,
	filename VARCHAR(255) NOT NULL,
	size INT NOT NULL,
	metadata JSON,
	created_at DATETIME DEFAULT NOW(),
	updated_at DATETIME DEFAULT NOW() ON UPDATE NOW()
);

DESCRIBE media;

CREATE TABLE media_types (
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE
);

DESCRIBE media;

SHOW TABLES;
DESCRIBE communities;
DESCRIBE communities;
USE vk;
DESCRIBE users;

